target: "results.db.compressed"

paths:
  gams: /opt/gams/gams46.5_linux_x64_64_sfx/
  shared_input: shared_input
  abs_shared_code: /home/runner/work/highRES-Europe-WF/highRES-Europe-WF/resources/highRES-Europe-GAMS/
  results: work

parameters:
  mode: [
    "normal", 
    #"developer", # Use this mode to run the model in developer mode
  ]
  years: [
    # "1995",
    "2010",
  ]
  spatials: [
    # "grid",
    "region",
    # "nuts2",
  ]
  bias_correction: False
  elevation_excl: False
  cutoff_solar: 0.09
  cutoff_onwind: 0.15
  cutoff_offwind: 0.20
  aggregated_regions: [
    "AT",
 #   "BE",
 #   "BG",
 #   "CH",
 #   "CZ",
    "DE",
#    "DK",
#    "EE",
#    "ES",
#    "FI",
#    "FR",
#    "UK",
#    "GR",
#    "HR",
#    "HU",
#    "IE",
#    "IT",
#    "LT",
#    "LU",
#    "LV",
#    "NL",
#    "NO",
#    "PL",
#    "PT",
#    "RO",
#    "SE",
#    "SI",
#    "SK",
  ]
  solar_clc : [
    1,
    2,
    4,
    5,
    6,
    10,
    11,
    23,
    24,
    25,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
  ]
  onwind_clc_no_buffer : [
    3,
    4,
    5,
    7,
    8,
    9,
    10,
    11,
    23,
    24,
    25,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
  ]
  onwind_clc_buffer : {
    1 : 1000,
    2 : 1000,
    6 : 5000,
  }
  co2target : [
    2 # gCO2/kWh
  ]

cplex_options:
  lpmethod: 4
  solutiontype: 2
  threads: 4
  predual: -1
  aggind: 50
  BarColNZ: 150
  barstartalg: 3
  BarOrder: 3