target: "results.db.compressed"

paths:
  gams: /opt/gams/gams50.1_linux_x64_64_sfx/
  shared_input: shared_input
  abs_shared_code: /home/runner/work/highRES-Europe-WF/highRES-Europe-WF/resources/highRES-Europe-GAMS/
  results: work

parameters:
  mode: [
    "normal", 
    #"developer", # Use this mode to run the model in developer mode
  ]
  years: [
    # "1995",
    "2010",
  ]
  spatials: [
    # "grid",
    "region",
    # "nuts2",
  ]

  power_system_scenario: ["BASE"]

  # Options: "intensity", "budget"
  co2_target_type: "intensity"
  
  # Options: "all"
  co2_target_extent: "all"

  # Options: "OFF","TYNDP","USER"
  trans_inv: "TYNDP"
  
  # Only used if trans_inv set to USER
  trans_cap_lim: 20
  
  bias_correction: True

  elevation_excl: False
  onshore_slope_excl: True
  include_rooftop: True

  emis_price: 0
  store_initial_level: 0.5
  store_final_level: 0.5
  hydro_res_initial_fill: 0.8
  hydro_res_min: 0.5
  pgen: 20.0

  cutoff_solar: 0.09
  cutoff_onwind: 0.1
  cutoff_offwind: 0.20
  date_range: ["01-01", "06-30"]
  aggregated_regions: [
    "AT",
    #"BE",
    #"BG",
    "CH",
    "CZ",
    "DE",
    #"DK",
    #"EE",
    #"ES",
    #"FI",
    "FR",
    #"UK",
    #"GR",
    #"HR",
    #"HU",
    #"IE",
    #"IT",
    #"LT",
    "LU",
    #"LV",
    #"NL",
    #"NO",
    "PL",
    #"PT",
    #"RO",
    #"SE",
    #"SI",
    #"SK",
  ]
  solar_clc : [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    23,
    24,
    25,
    30,
    31,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
  ]
  onwind_clc_no_buffer : [
    3,
    4,
    5,
    7,
    8,
    9,
    10,
    11,
    23,
    24,
    25,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
  ]
  onwind_clc_buffer : {
    1 : 1000,
    2 : 1000,
    6 : 5000,
  }
  windturbines : {
    "onshore" : "Vestas_V112_3MW",
    "offshore_bottom" : "NREL_ReferenceTurbine_2020ATB_15MW_offshore",
    "offshore_float" : "NREL_ReferenceTurbine_2020ATB_15MW_offshore",
  }

  wind_smooth: False
  windon_af: 0.95
  windoff_bottom_af: 0.95

cplex_options:
  lpmethod: 4
  solutiontype: 2
  threads: 4
  predual: 1
  BarOrder: 0
  barepcomp: 1E-7