target: "results.db.compressed"

paths:
  gams: /opt/gams/gams46.5_linux_x64_64_sfx/
  shared_input: shared_input
  abs_shared_code: /home/runner/work/highRES-Europe-WF/highRES-Europe-WF/resources/highRES-Europe-GAMS/
  results: work

parameters:
  mode: [
    "normal", 
    #"developer", # Use this mode to run the model in developer mode
  ]
  years: [
    # "1995",
    "2010",
  ]
  spatials: [
    # "grid",
    # "region",
    "nuts2",
  ]

  environmental: [
   # "low",
   "medium",
    # "high",
  ]
  social: [
   # "low",
   "medium",
    # "high",
  ]  
  wimby_outputs: False
  wimby_outputs_hourly: True
  
  bias_correction: False
  elevation_excl: False
  #CMIP - PECD
  cmip_years: [
    # 2010, # only with cmip_models ERA5
    2050,
    # 2051,
  ]
  cmip_models: [
    # "ERA5",
    "CMCC_CMR5",
    # "MPI-_MEHR",
  ]
  cmip_windspeed: True
  cmip_solar: True
  cmip_windspeed_path: "/fp/homes01/u01/ec-guillerv/wimby/Europe_v1/data/PECD/cmip/ssp245/"
  # cmip_windspeed_path: "/fp/homes01/u01/ec-guillerv/wimby/Europe_v1/data/PECD/ERA5/"
  cmip_solar_cf_path: "/fp/homes01/u01/ec-guillerv/wimby/Europe_v1/data/PECD/cmip/ssp245/"
  # cmip_solar_cf_path: "/fp/homes01/u01/ec-guillerv/wimby/Europe_v1/data/PECD/ERA5/"

  wind_smooth: False
  windon_af: 0.95
  windoff_bottom_af: 0.95

  onshore_slope_excl: True
  include_rooftop: True
  cutoff_solar: 0.09
  cutoff_onwind: 0.15
  cutoff_offwind: 0.20
  co2target: 2 # gCO2/kWh
  emis_price: 0
  store_initial_level: 0.5
  store_final_level: 0.5
  hydro_res_initial_fill: 0.8
  hydro_res_min: 0.5
  pgen: 20.0
  date_range: ["01-01", "06-30"]
  aggregated_regions: [
    #"AT",
    #"BE",
    "BG",
    #"CH",
    #"CZ",
    #"DE",
    #"DK",
    "EE",
    "ES",
    "FI",
    "FR",
    "UK",
    "GR",
    "HR",
    "HU",
    "IE",
    "IT",
    "LT",
    #"LU",
    "LV",
    #"NL",
    "NO",
    "PL",
    "PT",
    "RO",
    #"SE",
    #"SI",
    "SK",
  ]
  solar_clc : [
    1,
    2,
    4,
    5,
    6,
    10,
    11,
    23,
    24,
    25,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
  ]
  onwind_clc_no_buffer : [
    3,
    4,
    5,
    7,
    8,
    9,
    10,
    11,
    23,
    24,
    25,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
  ]
  onwind_clc_buffer : {
    1 : 1000,
    2 : 1000,
    6 : 5000,
  }
  windturbines : {
    "onshore" : "Vestas_V112_3MW",
    "offshore_bottom" : "NREL_ReferenceTurbine_2020ATB_15MW_offshore",
    "offshore_float" : "NREL_ReferenceTurbine_2020ATB_15MW_offshore",
  }

cplex_options:
  lpmethod: 4
  solutiontype: 2
  threads: 4
  predual: -1
  aggind: 50
  BarColNZ: 150
  barstartalg: 3
  BarOrder: 3