name: highres
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - jupyter
  - jupyterlab_code_formatter
  - black
  - isort
  - odfpy
  - numpy
  - pandas
  - pyarrow
  - rioxarray
  - xlrd
  - odfpy
  - numpy-financial
  - fastparquet
  - snakemake-minimal
  - zstd
  - pycountry
  - numpy
  - xarray=2024.3.0
  - pandas
  - shapely
  - matplotlib
  - git
  - pip
  - pip:
    - cdsapi
    - git+https://github.com/absolute-afloat/atlite.git@hr